# playbook.yml
---
- hosts: all
  sudo: yes
  tasks:
    - name: 1. install Apache
      apt: name=apache2 state=present

    - name: 2. install PHP module for Apache
      apt: name=libapache2-mod-php5 state=present

    - name: 3. start Apache
      service: name=apache2 state=running enabled=yes

    - name: 4. Clone Git Repository
      git: repo=https://github.com/chrislewisdev/Birthdate-App.git dest=/var/www/birthdate

    - name: 5. Install postgres
      apt: name={{item}}
      with_items:
          - postgresql
          - libpq-dev
          - python-psycopg2

    - name: 6. Install postgres php extension
      apt: name=php5-pgsql state=present

- hosts: all
  sudo: yes
  sudo_user: postgres

  handlers:
    - name: restart postgresql
      service: name=postgresql state=restarted

  tasks:
    - name: 7. configure postgres to listen on all ports
      lineinfile: dest=/etc/postgresql/9.1/main/postgresql.conf
                regexp="^listen_addresses"
                line="listen_addresses = '*'" state=present

    - name: 8. configure postgres to allow access to host
      copy:
        dest: /etc/postgresql/9.1/main/pg_hba.conf
        content: |
          local   all   postgres   peer
          local   all   all        peer
          host    all   all        0.0.0.0/0   md5
      notify: restart postgresql

- hosts: all
  sudo: yes
  sudo_user: postgres

  vars:
    dbname: birthdate-db
    dbuser: rootuser
    dbpassword: secret

  tasks:
    - name: 10. Create postgres database
      postgresql_db: name={{dbname}}

    - name: 11. Create postgres user
      postgresql_user: name={{dbuser}} password={{dbpassword}} db={{dbname}} priv=ALL
